services:
  - type: web
    name: winpay999_bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7908773608:AAFFqLmGkJ9zbsuymQTFzJxy5IyeN1E9M-U
